package com.crm.redis_impl.config.exception.globalHandler;

import com.crm.redis_impl.config.exception.customException.InvalidArgumentException;
import com.crm.redis_impl.config.exception.customException.NotFoundException;
import com.crm.redis_impl.config.exception.customException.UnAuthorizedAccessxception;
import com.crm.redis_impl.dto.response.ApiResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

@RestControllerAdvice
public class GlobalExceptionHandler {

    private final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    // Ensures ALL errors generated by your REST API use your strict ApiResponse format
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiResponse> handleGeneralExceptions(Exception ex) {
        logger.error(ex.getMessage(), ex);
        ApiResponse response = new ApiResponse("false", ex.getMessage(), null);
        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(UnAuthorizedAccessxception.class)
    public ResponseEntity<ApiResponse> handleExceptions(UnAuthorizedAccessxception ex) {
        logger.error(ex.getMessage(), ex);
        ApiResponse response = new ApiResponse("false", ex.getMessage(), null);
        return new ResponseEntity<>(response, HttpStatus.UNAUTHORIZED);
    }

    @ExceptionHandler(InvalidArgumentException.class)
    public ResponseEntity<ApiResponse> handleExceptions(InvalidArgumentException ex) {
        logger.error(ex.getMessage(), ex);
        ApiResponse response = new ApiResponse("false", ex.getMessage(), null);
        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(NotFoundException.class)
    public ResponseEntity<ApiResponse> handleExceptions(NotFoundException ex) {
        logger.error(ex.getMessage(), ex);
        ApiResponse response = new ApiResponse("false", ex.getMessage(), null);
        return new ResponseEntity<>(response, HttpStatus.NOT_FOUND);
    }

}